### ISSUE TITLE
看到你在味精的文章里的评论

### ISSUE THREAD

**Issue by Guodadada** [CocoaKier/MacVPN#1]
没找到你的直接联系方式，希望加微信请教下你评论的方法
![501552747524_ pic_hd](https://user-images.githubusercontent.com/16527069/54476898-41767d00-483d-11e9-924a-9bb111c7a7cb.jpg)

**Comment by Guodadada** [comment]
我的微信 ic1225

**Comment by CocoaKier** [comment]
UIWebView已经废弃，WKWebView不存在此问题了
